services:
  redis-test:
    image: redis:8.8.0-alpine3.23
    command:
      - redis-server
      - --save
      - ''
      - --appendonly
      - 'no'
    profiles:
      - redis-test
    ports:
      - '6380:6379'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
