name: Setup Node Project
description: Set up Node.js with npm cache and install project dependencies.

inputs:
  node-version:
    description: Node.js version to install.
    required: false
    default: '20'

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
