const PROVIDER_VALIDATION_ASSETS = Object.freeze({
  'a.png': Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAABAKADAAQAAAABAAABAAAAAABn6hpJAAAE80lEQVR4Ae3TAQ0AIAwDwZEgFP8qCNj4W2ag3/6aOWvGI9AksN/2HQJVAgSoNi/3J0AAQ0gTIEC6fuEJYANpAgRI1y88AWwgTYAA6fqFJ4ANpAkQIF2/8ASwgTQBAqTrF54ANpAmQIB0/cITwAbSBAiQrl94AthAmgAB0vULTwAbSBMgQLp+4QlgA2kCBEjXLzwBbCBNgADp+oUngA2kCRAgXb/wBLCBNAECpOsXngA2kCZAgHT9whPABtIECJCuX3gC2ECaAAHS9QtPABtIEyBAun7hCWADaQIESNcvPAFsIE2AAOn6hSeADaQJECBdv/AEsIE0AQKk6xeeADaQJkCAdP3CE8AG0gQIkK5feALYQJoAAdL1C08AG0gTIEC6fuEJYANpAgRI1y88AWwgTYAA6fqFJ4ANpAkQIF2/8ASwgTQBAqTrF54ANpAmQIB0/cITwAbSBAiQrl94AthAmgAB0vULTwAbSBMgQLp+4QlgA2kCBEjXLzwBbCBNgADp+oUngA2kCRAgXb/wBLCBNAECpOsXngA2kCZAgHT9whPABtIECJCuX3gC2ECaAAHS9QtPABtIEyBAun7hCWADaQIESNcvPAFsIE2AAOn6hSeADaQJECBdv/AEsIE0AQKk6xeeADaQJkCAdP3CE8AG0gQIkK5feALYQJoAAdL1C08AG0gTIEC6fuEJYANpAgRI1y88AWwgTYAA6fqFJ4ANpAkQIF2/8ASwgTQBAqTrF54ANpAmQIB0/cITwAbSBAiQrl94AthAmgAB0vULTwAbSBMgQLp+4QlgA2kCBEjXLzwBbCBNgADp+oUngA2kCRAgXb/wBLCBNAECpOsXngA2kCZAgHT9whPABtIECJCuX3gC2ECaAAHS9QtPABtIEyBAun7hCWADaQIESNcvPAFsIE2AAOn6hSeADaQJECBdv/AEsIE0AQKk6xeeADaQJkCAdP3CE8AG0gQIkK5feALYQJoAAdL1C08AG0gTIEC6fuEJYANpAgRI1y88AWwgTYAA6fqFJ4ANpAkQIF2/8ASwgTQBAqTrF54ANpAmQIB0/cITwAbSBC6KJQZcdTSPIAAAAABJRU5ErkJggg==',
    'base64',
  ),
  'b.png': Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAABAKADAAQAAAABAAABAAAAAABn6hpJAAAE9UlEQVR4Ae3TAQ3AQAzDwFZ6IONPcnuNhq8qgTjxPvPOjkegSeDMFcAhUCVAgGrzcv8ECGAIaQIESNcvPAFsIE2AAOn6hSeADaQJECBdv/AEsIE0AQKk6xeeADaQJkCAdP3CE8AG0gQIkK5feALYQJoAAdL1C08AG0gTIEC6fuEJYANpAgRI1y88AWwgTYAA6fqFJ4ANpAkQIF2/8ASwgTQBAqTrF54ANpAmQIB0/cITwAbSBAiQrl94AthAmgAB0vULTwAbSBMgQLp+4QlgA2kCBEjXLzwBbCBNgADp+oUngA2kCRAgXb/wBLCBNAECpOsXngA2kCZAgHT9whPABtIECJCuX3gC2ECaAAHS9QtPABtIEyBAun7hCWADaQIESNcvPAFsIE2AAOn6hSeADaQJECBdv/AEsIE0AQKk6xeeADaQJkCAdP3CE8AG0gQIkK5feALYQJoAAdL1C08AG0gTIEC6fuEJYANpAgRI1y88AWwgTYAA6fqFJ4ANpAkQIF2/8ASwgTQBAqTrF54ANpAmQIB0/cITwAbSBAiQrl94AthAmgAB0vULTwAbSBMgQLp+4QlgA2kCBEjXLzwBbCBNgADp+oUngA2kCRAgXb/wBLCBNAECpOsXngA2kCZAgHT9whPABtIECJCuX3gC2ECaAAHS9QtPABtIEyBAun7hCWADaQIESNcvPAFsIE2AAOn6hSeADaQJECBdv/AEsIE0AQKk6xeeADaQJkCAdP3CE8AG0gQIkK5feALYQJoAAdL1C08AG0gTIEC6fuEJYANpAgRI1y88AWwgTYAA6fqFJ4ANpAkQIF2/8ASwgTQBAqTrF54ANpAmQIB0/cITwAbSBAiQrl94AthAmgAB0vULTwAbSBMgQLp+4QlgA2kCBEjXLzwBbCBNgADp+oUngA2kCRAgXb/wBLCBNAECpOsXngA2kCZAgHT9whPABtIECJCuX3gC2ECaAAHS9QtPABtIEyBAun7hCWADaQIESNcvPAFsIE2AAOn6hSeADaQJECBdv/AEsIE0AQKk6xeeADaQJkCAdP3CE8AG0gQIkK5feALYQJoAAdL1C08AG0gTIEC6fuEJYANpAgRI1y88AWwgTYAA6fqFJ4ANpAkQIF2/8ASwgTQBAqTrF54ANpAmQIB0/cITwAbSBAiQrl94AthAmgAB0vULTwAbSBMgQLp+4QlgA2kCBEjXLzwBbCBNgADp+oUngA2kCRAgXb/wBLCBNAECpOsXngA2kCZAgHT9whPABtIECJCuX3gC2ECaAAHS9QtPABtIEyBAun7hCWADaQIESNcvPAFsIE2AAOn6hSeADaQJECBdv/AEsIE0AQKk6xeeADaQJkCAdP3CE8AG0gQIkK5feALYQJrABzYBBCyTQfI8AAAAAElFTkSuQmCC',
    'base64',
  ),
});

const PROVIDER_VALIDATION_PAGE_TITLE = 'Alt Text Provider Validation Fixture';

/**
 * @param {string} name
 * @returns {Buffer | null}
 */
function getProviderValidationAsset(name) {
  return PROVIDER_VALIDATION_ASSETS[name] || null;
}

/**
 * @param {string} baseUrl
 * @returns {string}
 */
function buildProviderValidationPageHtml(baseUrl) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${PROVIDER_VALIDATION_PAGE_TITLE}</title>
  </head>
  <body>
    <h1>${PROVIDER_VALIDATION_PAGE_TITLE}</h1>
    <img src="/provider-validation/assets/a.png" alt="" />
    <img src="${baseUrl}/provider-validation/assets/b.png" alt="" />
    <img src="/provider-validation/assets/a.png" alt="" />
  </body>
</html>`;
}

module.exports = {
  buildProviderValidationPageHtml,
  getProviderValidationAsset,
  PROVIDER_VALIDATION_PAGE_TITLE,
};
